package vistas;

/**
 *
 * @author bruno
 */

import javax.swing.table.DefaultTableModel;
import modelo.Producto;
import modelo.ProductoDAO;
import java.util.List;
import javax.swing.JOptionPane;

public class ProductosForm extends javax.swing.JInternalFrame {

    ProductoDAO pdao=new ProductoDAO(); //instancio producto y productodao
    Producto pr=new Producto();
    DefaultTableModel modelo= new DefaultTableModel();
    int codp;  //Esto es CodigoProducto
    
    public ProductosForm() {
        initComponents();
         listar(); //Pido que se ejecute al iniciar el modulo
    } //Fin de ProductosForm
    
     void listar(){
        List<Producto> lista=pdao.listar();
        modelo=(DefaultTableModel) tablaProducto.getModel();
        Object[] ob = new Object[7];
        
        for (int i = 0; i < lista.size(); i++){
            
            Producto pr = (Producto) lista.get(i);
            
            ob[0]=pr.getCodProducto();
            ob[1]=pr.getNombre();
            ob[2]=pr.getDescripcion();
            ob[3]=pr.getPrecio();
            ob[4]=pr.getStock();
            ob[5]=pr.getCodRubro();
            
            modelo.addRow(ob);
            
        
        }//fin del FOR
        
        tablaProducto.setModel(modelo);
    }//Fin de Listar

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreP = new javax.swing.JTextField();
        txtDescP = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtRubro = new javax.swing.JTextField();
        btnAgregarP = new javax.swing.JButton();
        btnActualizarP = new javax.swing.JButton();
        btnEliminarP = new javax.swing.JButton();
        btnNuevoP = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();

        setTitle("SantaRita - Productos");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Nombre");

        jLabel2.setText("Descripcion");

        jLabel3.setText("Precio");

        jLabel4.setText("Stock");

        jLabel5.setText("Rubro");

        txtDescP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescPActionPerformed(evt);
            }
        });

        btnAgregarP.setText("Agregar");
        btnAgregarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPActionPerformed(evt);
            }
        });

        btnActualizarP.setText("Actualizar");
        btnActualizarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPActionPerformed(evt);
            }
        });

        btnEliminarP.setText("Eliminar");
        btnEliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPActionPerformed(evt);
            }
        });

        btnNuevoP.setText("Nuevo");
        btnNuevoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(txtNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescP)
                            .addComponent(txtPrecio)
                            .addComponent(txtStock)
                            .addComponent(txtRubro))))
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgregarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarP, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnActualizarP, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(btnNuevoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtDescP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnActualizarP, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                    .addComponent(btnAgregarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnNuevoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(btnEliminarP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodProducto", "Nombre", "Descripcion", "Precio", "Stock"
            }
        ));
        tablaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProducto);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPActionPerformed
        // Boton para el Metodo Agregar
        //Luego de Agregar un elmento, limpio la tabla y llamo a listar nuevamente para mostrar los datos nuevos
        agregar();
        limpiarTabla(); 
        listar();
        nuevo();
        
    }//GEN-LAST:event_btnAgregarPActionPerformed

    private void txtDescPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescPActionPerformed

    private void btnActualizarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPActionPerformed
        // boton actualizar
        actualizar();
        limpiarTabla();
        listar();
        nuevo();
    }//GEN-LAST:event_btnActualizarPActionPerformed

    private void btnEliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPActionPerformed
        // boton eliminar
        eliminar();
        limpiarTabla();
        listar();
        nuevo();
    }//GEN-LAST:event_btnEliminarPActionPerformed

    private void btnNuevoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPActionPerformed
        // Boton nuevo 
         nuevo();
    }//GEN-LAST:event_btnNuevoPActionPerformed

    private void tablaProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductoMouseClicked
        // Evento de clic sobre la tabla productos! 
        
        int fila=tablaProducto.getSelectedRow();
        if (fila==-1) {  //esta condición es para saber si la fila está seleccionada o no
            JOptionPane.showMessageDialog(this,"Debe Seleccionar una Fila");
        }//Fin del IF
        else{ // Aqui el usuario si seleccionó la tabla
            //capturo los datos que están en las posiciones de la TAbla
             this.codp = Integer.parseInt(tablaProducto.getValueAt(fila,0).toString());
             String nom= tablaProducto.getValueAt(fila,1).toString();
             String desc= tablaProducto.getValueAt(fila,2).toString();
             String prec= tablaProducto.getValueAt(fila,3).toString();
             String sto= tablaProducto.getValueAt(fila,4).toString();
           //  String ru= tablaProducto.getValueAt(fila,5).toString(); No debo actualizar rubro
           
             
             txtNombreP.setText(nom);
             txtDescP.setText(desc);
             txtPrecio.setText(prec);
             txtStock.setText(sto);
            // txtFecha.setText(fe); 
                        
        }       
    }//GEN-LAST:event_tablaProductoMouseClicked

    void agregar(){
    
        String nom= txtNombreP.getText();
        String desc= txtDescP.getText();
        String precStr= txtPrecio.getText();
        String stoStr= txtStock.getText();
        String ruStr= txtRubro.getText();     
        
        try {
        Double prec = Double.parseDouble(precStr);
        Integer sto = Integer.parseInt(stoStr);
        Integer ru = Integer.parseInt(ruStr);
                
        Object[] ob=new Object[5];
        
        ob[0]= nom;
        ob[1]=desc;
        ob[2]=prec;
        ob[3]=sto;
        ob[4]=ru;
                   
        pdao.add(ob); 
        JOptionPane.showMessageDialog(this, "Producto agregado con éxito.");
    } catch (NumberFormatException e) {
        // Manejar el error si el usuario no ingresó un número en Precio, Stock o Rubro.
        JOptionPane.showMessageDialog(this, "Error de formato: Asegúrese de que Precio, Stock y Rubro sean números válidos.", "Error de Entrada", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
        return; // Detener la ejecución si hay un error de formato
    }
        
    }//Fin de Agregar()
    
    void actualizar(){
        String nom= txtNombreP.getText();
        String desc= txtDescP.getText();
        String precStr = txtPrecio.getText();
        String stoStr = txtStock.getText();
        String ruStr = txtRubro.getText(); // Capturar Rubro
              
        if (nom.isEmpty() || desc.isEmpty() || precStr.isEmpty() || stoStr.isEmpty() || ruStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe completar todos los campos.", "Error de Datos", JOptionPane.WARNING_MESSAGE);
        return; // Detiene la ejecución si falta algún campo
    }
        
        try {
        // Conversión
        Double prec = Double.parseDouble(precStr);
        Integer sto = Integer.parseInt(stoStr);
        Integer ru = Integer.parseInt(ruStr); // Rubro 
        
        Object[] obj=new Object [6];
        
        obj[0]=nom;
        obj[1]=desc;
        obj[2]=prec;
        obj[3]=sto; 
        obj[4]=ru;     
        obj[5]=codp;   
        
        pdao.actualizar(obj);
        JOptionPane.showMessageDialog(this, "Producto Actualizado con éxito.");
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error de formato en números.");
        e.printStackTrace();
    }
    }//Fin de Actualizar()
    
    void eliminar(){
        int fila=tablaProducto.getSelectedRow();
        if (fila==-1){
            JOptionPane.showMessageDialog(this,"Debe seleccionar una fila");
        
        }//fin del IF
        else{
            pdao.eliminar(codp);
        
        }//fin del else
    
    }//Fin de Eliminar
    
    void nuevo(){
             txtNombreP.setText("");
             txtDescP.setText("");
             txtPrecio.setText("");
             txtStock.setText("");
             txtRubro.setText("");
            //txt.requestFocus();
    
    }//fin de nuevo 
    
    //Este metodo es Para limpiar los valores de la tablar al agregar clientes
    
    void limpiarTabla(){
        for (int i = 0; i < modelo.getRowCount(); i++){
            modelo.removeRow(i);;
            i=i-1;
        
        }//Fin del for
    
    }//Fin de LimpiarTabla

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarP;
    private javax.swing.JButton btnAgregarP;
    private javax.swing.JButton btnEliminarP;
    private javax.swing.JButton btnNuevoP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProducto;
    private javax.swing.JTextField txtDescP;
    private javax.swing.JTextField txtNombreP;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtRubro;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
