package vistas;

/**
 *
 * @author bruno
 */
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.ClienteDAO;
import modelo.DetallePedido;
import modelo.ProductoDAO;
import modelo.DetallePedidoDAO;
import modelo.PedidoCliente;
import modelo.PedidoClienteDAO;
import modelo.Producto;


public class VentasForm extends javax.swing.JInternalFrame {

    DetallePedidoDAO dpdao= new DetallePedidoDAO();//NO
    
    PedidoCliente pc= new PedidoCliente();
    PedidoClienteDAO pcdao = new PedidoClienteDAO();
    DetallePedido dep= new DetallePedido();
    ClienteDAO cdao=new ClienteDAO();
    ProductoDAO pdao=new ProductoDAO();
    Producto p=new Producto();
    DefaultTableModel modelo= new DefaultTableModel();
    Cliente cliente=new Cliente();
    int idp;
    double pre;
    int cant;
    double tpagar;
    
    
    public VentasForm() {
        initComponents();
        Calendar calendar=new GregorianCalendar();
        txtFecha.setText(""+calendar.get(Calendar.YEAR)+"-"+calendar.get(Calendar.MONTH)+"-"+calendar.get(Calendar.DAY_OF_MONTH));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarDni = new javax.swing.JButton();
        txtDniCli = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDatosCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCodProdu = new javax.swing.JTextField();
        btnBuscarProd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtDatosProd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPrecioProd = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        SpinnerCantidad = new javax.swing.JSpinner();
        txtFecha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtStockProd = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVenta = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnGenerarVenta = new javax.swing.JButton();

        setTitle("SantaRita - Ventas");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("DNI Cliente");

        btnBuscarDni.setText("Buscar");
        btnBuscarDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDniActionPerformed(evt);
            }
        });

        jLabel2.setText("Cliente");

        jLabel3.setText("Cod. Producto");

        btnBuscarProd.setText("Buscar");
        btnBuscarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdActionPerformed(evt);
            }
        });

        jLabel4.setText("Producto");

        jLabel5.setText("Precio");

        txtPrecioProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioProdActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel6.setText("Cantidad");

        jLabel7.setText("Stock");

        jLabel8.setText("Fecha");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodProdu)
                            .addComponent(txtDniCli, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarDni)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btnBuscarProd))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SpinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtPrecioProd, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregar)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatosProd, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStockProd, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDniCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarDni)
                    .addComponent(jLabel2)
                    .addComponent(txtDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodProdu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnBuscarProd)
                    .addComponent(jLabel4)
                    .addComponent(txtDatosProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnAgregar)
                    .addComponent(jLabel7)
                    .addComponent(txtStockProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tablaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro", "Cod Prod", "Producto", "Cantidad", "Precio Unitario", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(tablaVenta);

        jLabel9.setText("Total a Pagar");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGenerarVenta.setText("Generar Venta");
        btnGenerarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGenerarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGenerarVenta))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtPrecioProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioProdActionPerformed

    private void btnBuscarDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDniActionPerformed
        // Boton BuscarCliente       
         buscarCliente();
    }//GEN-LAST:event_btnBuscarDniActionPerformed

    private void btnBuscarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdActionPerformed
        // Boton buscar Producto
        
        buscarProducto();
    }//GEN-LAST:event_btnBuscarProdActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // Boton Agregar Producto  a la lista
        agregarProducto();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnGenerarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarVentaActionPerformed
        // BotonGenerarVenta
        guardarPedidoCliente(); 
        guardarDetallePedido();      
          JOptionPane.showMessageDialog(null, "¡Venta Exitosa!");
   
         
    }//GEN-LAST:event_btnGenerarVentaActionPerformed

       
    void guardarPedidoCliente(){
         
            int idc=cliente.getCodCliente(); //codigocliente
            double monto=tpagar;
            String fecha=txtFecha.getText();        
            pc.setCodCliente(idc);
            pc.setMonto(monto);
            pc.setFecha(fecha);            
            pcdao.guardarPedidoC(pc);           
    
    }//fin guardarppedidoCliente
          
   
    void guardarDetallePedido(){
        String idpc=pcdao.IdPedidoC();
        int idpce=Integer.parseInt(idpc);
        
        for(int i=0; i< tablaVenta.getRowCount(); i++){
            int idpro=Integer.parseInt(tablaVenta.getValueAt(i, 1).toString());
            int cant=Integer.parseInt(tablaVenta.getValueAt(i, 3).toString());
            double pre= Double.parseDouble(tablaVenta.getValueAt(i,4).toString());
            dep.setCodPedidod(idpce);
            dep.setCodProductod(idpro);
            dep.setMontoD(pre);
            dep.setCantidad(cant);
            
            pcdao.GuardarDetallePe(dep);
        }
        
    }//Fin guardarDetallePedido
    
    
  //------------------------------------------------  
    void agregarProducto(){
        double total;
        int item=0;
        modelo=(DefaultTableModel)tablaVenta.getModel();
        item=item+1;
        idp=p.getCodProducto(); //aqui capturo el id del producto
        String nomp=txtDatosProd.getText();
        pre= Double.parseDouble(txtPrecioProd.getText());
        cant=Integer.parseInt(SpinnerCantidad.getValue().toString());
        int stock=Integer.parseInt(txtStockProd.getText());
        total=cant*pre;
        ArrayList lista = new ArrayList();
        if(stock>0){
            lista.add(item);
            lista.add(idp);
            lista.add(nomp);
            lista.add(cant);
            lista.add(pre);
            lista.add(total);
            
            Object[] ob = new Object[6];
            ob[0]=lista.get(0);
            ob[1]=lista.get(1);
            ob[2]=lista.get(2);
            ob[3]=lista.get(3);
            ob[4]=lista.get(4);
            ob[5]=lista.get(5);
            modelo.addRow(ob);
            tablaVenta.setModel(modelo);
            calcularTotal();
            
        }else{
            JOptionPane.showMessageDialog(this, "El stock del producto no está disponible");
        }
        
    
    }//Fin de AgregarProducto
    
    void calcularTotal(){
    tpagar=0;
    for(int i=0; i< tablaVenta.getRowCount(); i++){
            cant=Integer.parseInt(tablaVenta.getValueAt(i, 3).toString());
            pre=Double.parseDouble(tablaVenta.getValueAt(i, 4).toString());
            tpagar=tpagar+ (cant*pre);
    }
    txtTotal.setText(""+tpagar);
    
    }//fin de CalcularTotal
    
    void buscarProducto() {
        
        String codProStr = txtCodProdu.getText();       
        if (codProStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el Código del Producto");
            txtCodProdu.requestFocus();
            return; 
        }
        try {
       
            int codpro = Integer.parseInt(codProStr);            
            Producto productoEncontrado = pdao.listarID(codpro);            
            if (productoEncontrado.getCodProducto() > 0) {               
                this.p = productoEncontrado;                                
                txtDatosProd.setText(productoEncontrado.getNombre());                
                txtPrecioProd.setText(String.valueOf(productoEncontrado.getPrecio())); 
                txtStockProd.setText(String.valueOf(productoEncontrado.getStock()));                               
            } else {
                JOptionPane.showMessageDialog(this, "Producto no registrado.");
                txtCodProdu.requestFocus();               
                txtDatosProd.setText("");
                txtPrecioProd.setText("");
                txtStockProd.setText("");
            }            
        } catch (NumberFormatException e) {            
            JOptionPane.showMessageDialog(this, "El Código debe ser un número entero válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            txtCodProdu.requestFocus();
        }
    } // fin buscarProducto
    
       
    void buscarCliente(){
    int r;
    String dniC = txtDniCli.getText();  
    
    if(dniC.isEmpty()){ 
        JOptionPane.showMessageDialog(this, "Debe ingresar DNI");       
        return; 
    }    
    Cliente clienteEncontrado = cdao.listarID(dniC);     
    // Verifico si el cliente fue encontrado 
    if(clienteEncontrado.getDniC() != null && !clienteEncontrado.getDniC().isEmpty()){
        this.cliente = clienteEncontrado;         
        txtDatosCliente.setText(this.cliente.getNomC() + " " + this.cliente.getApeC()); // Mejor mostrar nombre y apellido
        txtDatosProd.requestFocus();        
    } else {
        // Cliente NO encontrado
        r = JOptionPane.showConfirmDialog(this, "Cliente No Registrado. ¿Desea Registrarlo?");        
        if(r == 0){ 
            ClientesForm cf = new ClientesForm();
            Principal.VentanaPrincipal.add(cf); 
            cf.setVisible(true);
        }     
        this.cliente = new Cliente(); 
    }
}    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpinnerCantidad;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarDni;
    private javax.swing.JButton btnBuscarProd;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGenerarVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaVenta;
    private javax.swing.JTextField txtCodProdu;
    private javax.swing.JTextField txtDatosCliente;
    private javax.swing.JTextField txtDatosProd;
    private javax.swing.JTextField txtDniCli;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtPrecioProd;
    private javax.swing.JTextField txtStockProd;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
